# Generated by Django 3.2.13 on 2023-09-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=100)),
                ('confia', models.CharField(choices=[('0', 'nada confiavel'), ('1', 'confiavel o suficiente'), ('2', 'eu morreria por esse troço')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lagostas_brabas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('release_date', models.IntegerField()),
                ('afiliacao_partidaria', models.CharField(max_length=70)),
            ],
        ),
    ]
