# Generated by Django 3.2.13 on 2023-09-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotiva_bonda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabelados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('preco', models.IntegerField()),
            ],
        ),
    ]
