# Generated by Django 3.2.13 on 2023-09-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotiva_bonda', '0002_tabelados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=3)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
